version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 524147404421.dkr.ecr.eu-west-1.amazonaws.com
  build:
    commands:
      - docker build -t nest-app .
      - docker tag nest-app:latest 524147404421.dkr.ecr.eu-west-1.amazonaws.com/nest-app:latest
  post_build:
    commands:
      - docker push 524147404421.dkr.ecr.eu-west-1.amazonaws.com/nest-app:latest