apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nest-app
  name: nest-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nest-app
  template:
    metadata:
      labels:
        app: nest-app
    spec:
      containers:
        - image: 524147404421.dkr.ecr.eu-west-1.amazonaws.com/nest-app:latest
          name: nest-app
          ports:
            - containerPort: 3000
