apiVersion: v1
kind: Service
metadata:
  labels:
    app: nest-app
  name: nest-app
spec:
  ports:
    - name: 'http'
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: nest-app
  type: NodePort
